'use strict';

document.querySelector('.map').classList.remove('map--faded');

var cards = {
  author: {avatar: ['img/avatars/user01.png',
    'img/avatars/user02.png',
    'img/avatars/user03.png',
    'img/avatars/user04.png',
    'img/avatars/user05.png',
    'img/avatars/user06.png',
    'img/avatars/user07.png',
    'img/avatars/user08.png']},
  offer: {
    title: ['Красивая уютная квартира',
      'Большой загородный дом',
      'Обычный серый дом',
      'Огромный золотой дворец',
      'Уютная семейная квартирка',
      'Стандартный деревянный дом',
      'Нестандартный дом из кирпича',
      'Загородный коттедж'
    ],
    address: ['600, 350',
      '500, 350',
      '400, 450',
      '300, 550',
      '200, 250',
      '600, 450',
      '500, 550',
      '400, 450'],
    price: ['1000',
      '2000',
      '3000',
      '4000',
      '5000',
      '6000',
      '7000',
      '8000'],
    type: ['palace',
      'flat',
      'house',
      'bungalo'],
    rooms: ['',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8'],
    guests: ['11',
      '12',
      '13',
      '14',
      '15',
      '16',
      '17',
      '18'],
    checkin: ['12:00',
      '13:00',
      '14:00'],
    checkout: ['12:00',
      '13:00',
      '14:00'],
    features: ['wifi',
      'dishwasher',
      'parking',
      'washer',
      'elevator',
      'conditioner'],
    description: [],
    photos: ['http://o0.github.io/assets/images/tokyo/hotel1.jpg',
      'http://o0.github.io/assets/images/tokyo/hotel2.jpg',
      'http://o0.github.io/assets/images/tokyo/hotel3.jpg']
  },
  location: {x: [], y: []},
};

var mapPinTemplate = document.querySelector('#pin')
  .content
  .querySelector('.map_pin');
